### ISSUE TITLE
PyQt5 support

### ISSUE THREAD

**Issue by rexissimus** [remram44/file_archive#28]
[viewer.py](https://github.com/remram44/file_archive/blob/master/file_archive/viewer.py) can probably be made to support both PyQt4 and PyQt5.

**Comment by remram44** [comment]
Fixed with b713e34b.

I'm using the `QT_API` environment variable, like other libraries do ([matplotlib](https://github.com/matplotlib/matplotlib/blob/v1.5.1/lib/matplotlib/backends/qt_compat.py#L18-L19), [ipython](https://github.com/jupyter/qtconsole/blob/4.1.1/qtconsole/qt_loaders.py#L25-L30)); VisTrails should probably set it to 'pyqt5'.

**Comment by rexissimus** [comment]
VisTrails is already using QT_API.
